config/routes.rb
Bunjy::Application.routes.draw do
  root :to => "home#index"

  # User Land
  resources :users
  resources :payments, :only => [:index, :show, :new, :create]
  resources :withdrawals, :only => [:index, :show, :new, :create]
  resources :payment_methods
  get '/locked' => 'users#locked'

  # API Land
  namespace :api do
    namespace :v1 do
      resources :users
      resources :payments
      resources :payment_methods
      resources :withdrawals
    end
    match 'v:api/*path', :to => redirect("/api/v2/%{path}"), via: [:get, :post]
    match '*path', :to => redirect("/api/v2/%{path}"), via: [:get, :post]
  end

  # Mission Control
  get '/mission-control' => 'mission_control#index'
  get '/mission-control/users' => 'mission_control#users'
  get '/mission-control/payments' => 'mission_control#payments'
  get '/mission-control/withdrawals' => 'mission_control#withdrawals'
  get '/mission-control/settings' => 'mission_control#settings'

  # Settings
  get '/settings/edit/:id' => 'settings#edit'
  get '/settings/delete/:id' => 'settings#delete'
  get '/settings/new' => 'settings#new'
  post '/settings/update' => 'settings#update'
  post '/settings' => 'settings#create'

  # Auth
  match '/auth/:provider/callback' => 'sessions#create', via: [:get, :post]
  post '/auth' => 'sessions#create_with_email'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'
  get '/reset-password' => 'sessions#recover_password_form'
  post '/reset-password' => 'sessions#recover_password'
end

app/views/layouts/_footer.html.slim
script type="text/javascript" src="https://js.stripe.com/v2/"
javascript:
  Stripe.setPublishableKey('pk_test_xYYaEj62khThgvZ3OhZumpEx');
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51491234-1', 'bunjy.me');
  ga('send', 'pageview');

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div
      = content_tag :p, msg, style: "color: black;"

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top[role="navigation"]
  .container
    .navbar-header
      button.navbar-toggle data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only 
          | Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand[href="/" style="color: white;"]
        i.fa.fa-credit-card
        | &nbspBunjy
    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
- if user_signed_in?
  li
    = link_to 'Send Money', new_payment_path
  li
    = link_to 'Withdraw Money', new_withdrawal_path
  li
    = link_to 'Account Activity', payments_path
  li
    = link_to 'Sign out', signout_path
- else
  li
    = link_to 'Log In', signin_path
  li
    = link_to 'Sign Up', new_user_path

app/views/layouts/admin.html.slim
doctype html
html
  head
    meta[http-equiv="Content-Type" content="text/html; charset=UTF-8"]
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      | Bunjy | Mission Control
    link[href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"]
    link[href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"]
    style[type="text/css"]
      | .jqstooltip { position: absolute;left: 0px;top: 0px;visibility: hidden;background: rgb(0, 0, 0) transparent;background-color: rgba(0,0,0,0.6);filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000);-ms-filter: "progid:DXImageTransform.Microsoft.gradient(startColorstr=#99000000, endColorstr=#99000000)";color: white;font: 10px arial, san serif;text-align: left;white-space: nowrap;padding: 5px;border: 1px solid white;z-index: 10000;}.jqsfield { color: white;font: 10px arial, san serif;text-align: left;
    == stylesheet_link_tag "admin", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'admin', 'data-turbolinks-track' => true
  body.pace-done
    .pace.pace-inactive
      .pace-progress[data-progress-text="100%" data-progress="99" style="width: 100%;"]
        .pace-progress-inner
      .pace-activity
    #wrapper
      nav.navbar-default.navbar-static-side[role="navigation"]
        .sidebar-collapse
          ul#side-menu.nav
            li.nav-header
              .dropdown.profile-element
                span
                  img.img-circle alt="image" src=image_url('admin_profile_pic.png')
                a.dropdown-toggle[data-toggle="dropdown" href="#"]
                  span.clear
                    span.block.m-t-xs
                      strong.font-bold
                        | #{@user.name}
                    span.text-muted.text-xs.block
                      | #{@user.role_name}
              .logo-element
                |  Bunjy

            li
              a[href="/"]
                i.fa.fa-arrow-left
                span.nav-label
                  | Back to App            
            li
              a[href="/mission-control/users"]
                i.fa.fa-users
                span.nav-label
                  | Users
            li
              a[href="/mission-control/payments"]
                i.fa.fa-usd
                span.nav-label
                  | Payments 
            li
              a[href="/mission-control/withdrawals"]
                i.fa.fa-money
                span.nav-label
                  | Withdrawals
            li
              a[href="/mission-control/settings"]
                i.fa.fa-gear
                span.nav-label
                  | Settings
      #page-wrapper.gray-bg
        == yield

app/views/layouts/application.html.slim
doctype html
html[lang="en"]
  head
    meta[http-equiv="Content-Type" content="text/html; charset=UTF-8"]
    meta[charset="utf-8"]
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    meta[name="description" content="The Kick-Ass Way to Pay"]
    meta[name="author" content="Sam Sheffres"]
    title
      = content_for?(:title) ? yield(:title) : 'Bunjy'
    link[href="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet"]
    link[href="http://netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet"]
    == stylesheet_link_tag "application", :media => 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application', 'data-turbolinks-track' => true
    == csrf_meta_tags    
  body
    == render 'layouts/navigation'
    div style="background-color: #4BAAD3; height: 100%;"
      == yield
      == render 'layouts/footer'      